version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: pets_house
      POSTGRES_USER: pet_user
      POSTGRES_PASSWORD: pet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  spring-app:
    image: petshouse-app
    container_name: petshouse-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pets_house
      SPRING_DATASOURCE_USERNAME: pet_user
      SPRING_DATASOURCE_PASSWORD: pet_password
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
    driver: local
